name: ML Pipeline

on:
  push:
    branches:
      - "*"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc

      # Pull data
      - name: DVC Pull
        run: dvc pull

      # Train model
      - name: Train model
        env:
          MLFLOW_URI: ${{ secrets.MLFLOW_URI }}
        run: python train.py

      # Upload model_info.txt
      - name: Upload model info
        uses: actions/upload-artifact@v4
        with:
          name: model-info
          path: model_info.txt

  deploy:
    needs: validate
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mlflow

      # Download artifact
      - name: Download model info
        uses: actions/download-artifact@v4
        with:
          name: model-info

      # Check threshold
      - name: Check accuracy threshold
        env:
          MLFLOW_URI: ${{ secrets.MLFLOW_URI }}
        run: python check_threshold.py

      # Mock Docker build (REQUIRED EXACT FORMAT)
      - name: Mock Docker Build
        run: echo "Building Docker image for Run ID: $(cat model_info.txt)"